### ISSUE TITLE
fails to build with ghc-9.8.4

### ISSUE THREAD

**Issue by juhp** [jonascarpay/calligraphy#40]
```
       Building library for calligraphy-0.1.6..                                                                                     
       [14 of 19] Compiling Calligraphy.Phases.Parse                                                                                
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/calligraphy-0.1.6-7adcc4f61dae7360bbae47f3caa539ef697310af6c50e70929642a7a4a6f752d/sr
c/Calligraphy/Phases/Parse.hs:105:23: error: [GHC-83865]                                                                            
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’                                                                       
             Expected: GHC.Types.Unique.Unique -> Int             
               Actual: GHC.Types.Unique.Unique -> GHC.Word.Word64                                                                   
           • In the first argument of ‘(.)’, namely ‘GHC.getKey’  
             In the second argument of ‘(.)’, namely
               ‘GHC.getKey . GHC.nameUnique’
             In the expression: GHCKey . GHC.getKey . GHC.nameUnique
           |
       105 | ghcNameKey = GHCKey . GHC.getKey . GHC.nameUnique
           |                       ^^^^^^^^^^
```
