### PR TITLE
Fix build on GHC 9.10

### LINKED ISSUE #37: Build fails with GHC 9.10
```
Building library for calligraphy-0.1.6...
[ 1 of 19] Compiling Calligraphy.Prelude
[ 2 of 19] Compiling Calligraphy.Compat.GHC
[ 3 of 19] Compiling Calligraphy.Util.Lens
[ 4 of 19] Compiling Calligraphy.Compat.Lib
[ 5 of 19] Compiling Calligraphy.Phases.Search
[ 6 of 19] Compiling Calligraphy.Util.LexTree
[ 7 of 19] Compiling Calligraphy.Util.Optparse
[ 8 of 19] Compiling Calligraphy.Util.Printer
[ 9 of 19] Compiling Calligraphy.Compat.Debug
[10 of 19] Compiling Calligraphy.Util.Types
[11 of 19] Compiling Calligraphy.Phases.Render.Common
[12 of 19] Compiling Calligraphy.Phases.Render.Mermaid
[13 of 19] Compiling Calligraphy.Phases.Render.GraphViz
[14 of 19] Compiling Calligraphy.Phases.Parse
src/Calligraphy/Phases/Parse.hs:105:23: error: [GHC-83865]
    • Couldn't match type ‘ghc-internal-9.1001.0:GHC.Internal.Word.Word64’
                     with ‘Int’
      Expected: GHC.Types.Unique.Unique -> Int
        Actual: GHC.Types.Unique.Unique
                -> ghc-internal-9.1001.0:GHC.Internal.Word.Word64
    • In the first argument of ‘(.)’, namely ‘GHC.getKey’
      In the second argument of ‘(.)’, namely
        ‘GHC.getKey . GHC.nameUnique’
      In the expression: GHCKey . GHC.getKey . GHC.nameUnique
    |
105 | ghcNameKey = GHCKey . GHC.getKey . GHC.nameUnique
    |                       ^^^^^^^^^^

[15 of 19] Compiling Calligraphy.Phases.NodeFilter
[16 of 19] Compiling Calligraphy.Phases.EdgeCleanup
[17 of 19] Compiling Calligraphy.Phases.DependencyFilter
[18 of 19] Compiling Paths_calligraphy
Error: [Cabal-7125]
Failed to build calligraphy-0.1.6 (which is required by exe:calligraphy from calligraphy-0.1.6). See the build log above for details.
```

### PR DESCRIPTION
**Pull request by michaelpj**
The result type of `getKey` varies between an `Int` and a `Word`. Use `fromIntegral` to handle either.

Fixes #37.

### CODE REVIEW

**Comment by jonascarpay** [comment]
Thanks! Cherry-picked onto https://github.com/jonascarpay/calligraphy/pull/46
