### ISSUE TITLE
fails to build with ghc-9.4 for Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [jonascarpay/calligraphy#15]
```
Building library for calligraphy-0.1.3..                          
[ 3 of 16] Compiling Calligraphy.Compat.Lib                                                                                         

/var/stackage/work/unpack-dir/unpacked/calligraphy-0.1.3-307771ebc155176f83b616559925c8fe11c75b7aac351cb58edb01a696dd4163/src/Callig
raphy/Compat/Lib.hs:48:38: error:
    Data constructor not in scope:                                
      NCU :: ((NameCache -> (NameCache, b0)) -> IO b0) -> NameCache                                                                 
   |                                                              
48 | readHieFileCompat ref = readHieFile (NCU (atomicModifyIORef ref))                                                              
   |                                      ^^^                                          
```

**Comment by AriFordsham** [comment]
It's this GHC MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4951
